## This is a Gitlab CI (Continuous Integration) pipeline that will be used to help with:
# Build Management and Quality Management

image: node

default:
  tags:
    - docker

stages:          # List of stages for jobs, and their order of execution
  - lint
  - build
  #- test
  - deploy

####################################################
# LINT STAGE
####################################################

eslint:      #Name of the job
 stage: lint  #Tells job which stage it is
 image: python:3.10  #Tells job which docker image to use
 script:
    - pip install pre-commit==3.3.3
    - apt update && apt install -y --no-install-recommends git
    - pre-commit run --all-files

build:
  stage: build
  image: node:latest
  script:
    - cd ./software/realm-render
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: node:latest
  script:
    - cd ./software/realm-render
    - npm ci
    - npm run build
    - npm run deploy
