## This is a Gitlab CI (Continuous Integration) pipeline that will be used to help with:
# Build Management and Quality Management

image: node

default:
  tags:
    - docker

stages:          # List of stages for jobs, and their order of execution
  - lint
  #- build
  #- test
  #- deploy

####################################################
# LINT STAGE
####################################################

eslint:      #Name of the job
 stage: lint  #Tells job which stage it is
 script:
    # Install eslint
    - |
      npm install eslint \
      eslint-config-airbnb \
      eslint-config-prettier \
      eslint-plugin-flowtype \
      eslint-plugin-import \
      eslint-plugin-jsx-a11y \
      eslint-plugin-prettier \
      eslint-plugin-react
    # Run eslint
    - node_modules/eslint/bin/eslint.js .

