---
# ==================
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# pre-commit run --all-files
#
# ==================
exclude: "^node_modules"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=auto']
      - id: check-added-large-files
        args: ['--maxkb=500']
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: v3.9.0
  #   hooks:
  #     - id: reorder-python-imports
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types:
  #         - python
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0
    hooks:
      - id: eslint
        args: [--fix, "./software/realm-render/src/*.js"] # Fix all fixable ESLint violations in the repository
